# Generated by Django 2.0.2 on 2018-03-16 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=25)),
                ('Author_name', models.CharField(max_length=30)),
            ],
        ),
    ]
