# Generated by Django 2.0.2 on 2018-03-18 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 10, 54, 37, 364263)),
        ),
    ]
